on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Java CI with Maven
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        # Email from Heroku Account
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        # The appname to use for deploying/updating
        heroku_app_name: ${{secrets.HEROKU_APP}}
